# 遇见五十年后的自己

昔我往矣，杨柳依依。今我来思，雨雪霏霏。一个保险交易员有其独特于大众的时间偏好，
这种偏好称之为跨期交易偏好，他在过往与未来中穿梭，消解心中即时满足的渴，换之以绵密恒长的幸福心流。

我们因为生物之本能赋予当下的满足以极大的权重，在知觉上，在记忆中。
会计学和心理学的交叉领域中有个重要的概念叫“延迟折扣或者双曲线折扣(Hyperbolic Discounting)”，
它是指在有限的时间压力下，人们相比起未来的奖励给予当下的即时的奖励更高的优先级。
人类在进化中形成的双曲线折扣模型是一种变加速模型，遥远未来的贴现率在一开始的一小段以极大的加速度
衰减，越到后来加速度越小。相比而言，自然界中森林与鱼塘资源的衰减速度则更符合指数折扣模型(Exponential
Discounting)。

```{r echo=FALSE, results="show"}
hyperbolic_discount <- function(k_hyp, delay) {
  discount_hyp <- 1 / (1 + k_hyp %o% delay)
  return(discount_hyp)
}

exponential_discount <- function(k_exp, delay) {
  discount_exp <- exp(-k_exp %o% delay)
  return(discount_exp)
}

plot_discount <- function(delay, discount_hyp, discount_exp) {
  matplot(delay, discount_hyp, type = "l", col = "red", xlab = "Delay (years)", ylab = "Discount rate")
  matlines(delay, discount_exp, type = "l", col = "blue")
  legend("topright", legend = c("Hyperbolic discounting", "Exponential discounting"), col = c("red", "blue"), lty = 1)
}

k_hyp <- seq(0.01, 0.5, by = 0.01)
delay <- 1:50
discount_hyp <- hyperbolic_discount(k_hyp, delay)

k_exp <- seq(0.001, 0.05, by = 0.001)
discount_exp <- exponential_discount(k_exp, delay)

plot_discount(delay, discount_hyp, discount_exp)
```

任何非线性衍生品，都与时间相关。时间尤其是金融市场中的时间如流水，时而平缓，时而湍急。
它绝不是匀速运动，而是变加速运动，拥有极强的非线性特征。上世纪五十年代，某位MIT的名教授曾经天真地把自己根据开市价和收市价构建的数学模型进行交易，
他为自己制定的策略是：凡是市场上涨5%或更多，购买并且持有。下跌5%，抛售。回测结果显示他能大赚一笔但最后差点赔得倾家荡产。
该策略失败的主要原因是他忽略了日内价格的波动，这导致他想的是在上涨5%的时候买，但是市场上一下子跳到了7.5%，而想在下跌到5%卖出时，
市场根本不给他机会，直接跌超了5%。

如果我们承认自己对时间的觉知还留存着强烈的如动物般的及时满足的生物本能并且市场本身的时间运动规律与这种动物性不一致时，
那么如果能战胜自己让自己拥有独特的跨期时间偏好，比常人更加克制现在就要的冲动，便拥有了独特的优势。所谓胜人者有力，自胜者强。

知易行难。灵长类人科这一属出现距今约200万年，但是距今1万年左右，人类才开始了植物生产和人口数量的急剧增加。
司管理性推理和延迟满足的模块建成相比其他模块的时间可能只占到了1%。在相同问题上，进化时间较近的模块与
久远的和本能生存相关的模块会有截然不同的决策结果。如果用意志力强行说服自己必然失败，我们需要和自己的原始大脑玩一些心理游戏
来帮助他曾经在进化中资源极度稀缺环境下必不可少但是在当下已经过时的策略。

### 看一看老去的自己
跨期交易的决策难做是因为我们的情绪和身体感受对当下的环境和即时的回报非常强烈，但是对于未来时间段的自己
很难感同身受。心理学家Hal Hershfield和Daniel Goldstein于是画出了老年时你可能变成的样子，
他们发现当你真实看到自己的白发与皱纹时，你更愿意储蓄与为未来的不确定性囤积资源，构建冗余而不是提前消费。
佛法里也有白骨观的修炼方法，看到死去的自己，腐烂的自己，来帮助人们守戒，得定，开慧。

### 执行意图
心理学家Peter Gollwitzer采取了新范式创新帮助人们从目标意图变成了执行意图。比如不让人制定我想要减肥或者
我想要减掉25公斤的目标，而是强迫人们思考与目标有关的情境。“明天睁眼以后(时间)，我就要穿上床边的耐克鞋去校园(环境)旁边跑400米(行为)。”
“如果我心情感到愉悦时，我就会深蹲50磅。”它通过提前对行动的规划，降低你认知资源的消耗，加之高频率的重复成为一种生理本能。
你与未来的自己签一纸期权合约，把止损点、价格和回报时间都制定好，解耦了交易计划和交易执行的逻辑。自我的斗争变为了一种对未来自我慈爱的情绪。

## 推荐书目与核心概念
1. Hershfield, H. E., Goldstein, D. G., Sharpe, W. F., Fox, J., Yeykelis, L., Carstensen, L. L., & Bailenson, J. N. (2011). Increasing saving behavior through age-progressed renderings of the future self. Journal of marketing research, 48(SPL), S23-S37.

